services:
    _defaults:
        autowire: true
        autoconfigure: true

    HitcKit\AuthBundle\Controller\:
        resource: '../../Controller/*'
        tags: [ 'controller.service_arguments' ]

    HitcKit\AuthBundle\Services\:
        resource: '../../Services/*'

    HitcKit\AuthBundle\Security\LoginFormAuthenticator: ~
