services:
    _defaults:
        autowire: true
        autoconfigure: true

    HitcKit\AuthBundle\Controller\:
        resource: '../../Controller/*'
        tags: [ 'controller.service_arguments' ]

#    HitcKit\AuthBundle\Services\:
#        resource: '../../Services/*'

    HitcKit\AuthBundle\Repository\:
        resource: '../../Repository/*'

    HitcKit\AuthBundle\DataFixtures\:
        resource: '../../DataFixtures/*'

    HitcKit\AuthBundle\Security\LoginFormAuthenticator: ~

    HitcKit\AuthBundle\Routing\DividingLoader:
        tags: [routing.loader]
